version: '3'
services:
  jello:
    image: jellothompson.com:v0.1.0
    ports:
      - "8081:8080"
    networks:
      - rproxy
  winecraft:
    image: winecraft.dev:v0.1.0
    ports:
      - "8082:8080"
    networks:
      - rproxy
  nginx: 
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    networks:
      - rproxy
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  rproxy:
    name: rproxy

